name: API compatibility

# Pull requests are compared with their base commit, and pushes to main with the previous commit.
on:
  pull_request:
  push:
    branches: [main]

jobs:
  roseau:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - uses: alien-tools/roseau-action@inline-annotations
        with:
          current: src/main/java
          pom: pom.xml
          config: roseau.yaml
          ignored: .roseau/accepted-breaks.csv
          reports: HTML=roseau-reports/report.html,CSV=roseau-reports/report.csv
          roseau-version: v0.7.0
